### PR TITLE
Fix for 9.0.1 (Shadowlands)

### LINKED ISSUE #23: Fix for 9.0.1 (Shadowlands) SetBackdrop change
https://github.com/Talyrius/TinyDPS/blob/50a4a34646aeeb541c59382850833e6b63cea7d2/TinyDPS.lua#L1073

This is due to [a change in SetBackdrop](https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#backdrop-system-changes).

<details>
 <summary>Click to expand</summary>

``` lua
1x TinyDPS\TinyDPS-8.2.5.1.lua:1073: attempt to call method '?' (a nil value)
[string "@TinyDPS\TinyDPS-8.2.5.1.lua"]:1073: in main chunk

Locals:
tdpsL = <table> {
 resetClassColors = "Reset Class Colors"
 hideWhenSolo = "Hide When Solo"
 close = "Cancel"
 hideInPvP = "Hide In PvP"
 overallData = "Overall Data"
 hideInBattle = "Hide In Pet Battle"
 amount = "Amount"
 size = "Size"
 melee = "Melee"
 instance = "Instance"
 layout = "Layout"
 showDamage = "Show Damage"
 font = "Font"
 minimapButton = "Minimap Button"
 none = "None"
 shadow = "Shadow"
 helpVersion = "Version"
 ten = "10"
 targets = "      %i  Targets in Tooltips"
 party = "Party"
 thick = "Thick"
 raid = "Raid"
 showHealing = "Show Healing"
 short = "Short Format"
 spells = "      %i  Spells in Tooltips"
 barBackdrop = "Bar Backdrop"
 history = "      %i  Historic Fights"
 trackSpellDetails = "Track Spell Details"
 repPrefix = <table> {
 }
 rank = "Rank"
 fifteen = "15"
 whisper2 = "Whisper <Name>"
 frameBorder = "Frame Border"
 resetAllData = "Reset All Data"
 lastFight = "Last Fight"
 currentFight = "Current Fight"
 tipPrefix = <table> {
 }
 noData = "No data to report"
 noTarget = "Invalid or no target selected"
 helpMove = "move: hold shift and drag the frame"
 topAbilities = "Top Abilities"
 hideOutOfCombat = "Hide Out Of Combat"
 resetOnNewGroup = "Reset On New Group"
 top10 = "Top 10"
 frameBackdrop = "Frame Backdrop"
 helpResize = "resize: drag the bottom right corner"
 options = "Options"
 helpToggle = "toggle: type /tdps to hide or show"
 decrease = "Decrease"
 text = "Text"
 byPets = "By Pet(s)"
 growUpwards = "Grow Upwards"
 dimClassColors = "Dim Class Colors"
 personal = "Personal"
 allClear = "All data has been reset"
 say = "Say"
 height = "Height"
 helpParameters2 = "/tdps visiblebars <number> | reportlength <number>"
 percent = "Percent"
 top3 = "Top 3"
 nudge = "Nudge"
 current = "Current"
 guild = "Guild"
 topTargets = "Top Targets"
 empty = "<Empty>"
 refreshEverySecond = "Refresh Every Second"
 outline = "Outline"
 report = "Report"
 hideAlways = "Hide Always"
 fight = "Fight"
 mono = "Monochrome"
 various = "Various"
 thin = "Thin"
 hideInCombat = "Hide In Combat"
 oneYourself = "1 (Yourself)"
 swapBarTextColor = "Swap Bar/Text Color"
 helpParameters1 = "/tdps help | reset | damage | healing | whisper <name>"
 keepOnlyBossFights = "Keep Only Boss Fights"
 increase = "Increase"
 maximum = "Visible bars"
 allFight = "Overall     All Fights"
 dps = "DPS"
 unlimited = "? (Unlimited)"
 twenty = "20"
 spacing = "Spacing"
 top5 = "Top 5"
 colors = "Colors"
 channel = "Channel"
 whisper = "Whisper Target"
 bars = "Bars"
 five = "5"
 officer = "Officer"
}
bu = <table> {
}
bar = <table> {
}
px = nil
com = nil
maxValue = nil
barsWithValue = nil
scrollPos = 1
isMovingOrSizing = false
ttSpellMerge = <table> {
}
ttMobMerge = <table> {
}
ttSort = <table> {
}
cColor = nil
isBoss = <table> {
 12236 = true
 40788 = true
 24560 = true
 6168 = true
 99200 = true
 59915 = true
 60043 = true
 18835 = true
 62346 = true
 60491 = true
 56717 = true
 19219 = true
 34456 = true
 44819 = true
 32857 = true
 10813 = true
 12876 = true
 33113 = true
 25840 = true
 4425 = true
 6488 = true
 77325 = true
 13020 = true
 9038 = true
 76814 = true
 15275 = true
 15339 = true
 11261 = true
 59789 = true
 18708 = true
 26928 = true
 22898 = true
 22930 = true
 91784 = true
 11501 = true
 11517 = true
 9502 = true
 54544 = true
 98949 = true
 56719 = true
 19220 = true
 1717 = true
 13740 = true
 59150 = true
 55312 = true
 27696 = true
 90378 = true
 76177 = true
 59726 = true
 16011 = true
 16059 = true
 11981 = true
 17941 = true
 52498 = true
 44566 = true
 103685 = true
 12237 = true
 98696 = true
 12397 = true
 24850 = true
 24882 = true
 60047 = true
 81297 = true
 39705 = true
 12557 = true
 10558 = true
 3669 = true
 14684 = true
 93068 = true
 21268 = true
 34460 = true
 91789 = true
 49045 = true
 34780 = true
 5401 = true
 69017 = true
 17910 = true
 17942 = true
 62543 = true
 9039 = true
 101002 = true
 7608 = true
 15276 = true
 95885 = true
 15340 = true
 75927 = true
 24723 = true
 33118 = true
 15516 = true
 5721 = true
 20885 = true
 11486 = true
 7800 = true
 11518 = true
 34014 = true
 21269 = 
```
</details>

### PR DESCRIPTION
**Pull request by spiralofhope**
Fix for [SetBackdrop changes](https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#backdrop-system-changes).

Fixes https://github.com/Talyrius/TinyDPS/issues/23

### CODE REVIEW

File: TinyDPS.lua [hunk 1]
```diff
@@ -2379,7 +2379,7 @@ local function newBar(g)
   dummybar:SetWidth(tdpsFrame:GetWidth() - 4)
   dummybar:SetHeight(tdps.barHeight)
   dummybar:Hide()
-  --dummybar:SetPoint("RIGHT", tdpsFrame, "RIGHT", -2, 0)
```
Comment (spiralofhope) [inline TinyDPS.lua:2382]: I'm not sure why this was commented-out.  TidyBar seems to work with it uncommented.
